#!/usr/bin/with-contenv bash

# Clone directory, If Directory Exists, Git Pull
if [[ ! -d /config/www/logarr/.git ]]; then
  echo '---------------------'
  echo '| Installing Logarr |'
  echo '---------------------'
  git clone -b docker-alpha --single-branch https://github.com/Monitorr/logarr.git /config/www/logarr
elif [[ -d /config/www/logarr/.git ]]; then
  echo '-------------------'
  echo '| Updating Logarr |'
  echo '-------------------'
  cd /config/www/logarr || return
  git reset --hard
  git pull --rebase
fi

# Make Directories
# USER DATA
echo 'Processing /app/userdata/ . . .'
if [[ ! -d /app/userdata/ ]]; then
  echo '-----------------------------------'
  echo '| No User Data Directory Detected |'
  echo '-----------------------------------'
  mv /config/www/logarr/assets/data/ /app/userdata
elif [[ -d /app/userdata/ ]]; then
  echo '--------------------------------'
  echo '| User Data Directory Detected |'
  echo '--------------------------------'
  rm -rf /config/www/logarr/assets/data
else
  :
fi
sleep 1
# DATA DIR Check
echo 'Processing /app/datadir.json . . .'
if [[ ! -e /app/datadir.json ]]; then
  echo '----------------------------------------------'
  echo '| No /app/datadir.json detected. Creating... |'
  echo '----------------------------------------------'
  cp /datadir.json /app/datadir.json
elif [[ -e /app/datadir.json ]]; then
  echo '---------------------------------------'
  echo '| We have detected /app/datadir.json! |'
  echo '---------------------------------------'
  rm -rf /config/www/logarr/assets/data/datadir.json
else
  :
fi
sleep 1

echo '------------------------------'
echo '| Linking Data Dir to Logarr |'
echo '------------------------------'
sleep 3
ln -s  /app/datadir.json /config/www/monitorr/assets/data/datadir.json
ln -s  /app/userdata/ /config/www/logarr/assets/data
echo 'Installation Complete. Thanks for using Logarr!'
sleep 1


# Permissions
chown -R abc:abc /config
chown -R abc:abc /app
chmod -R 777 /app/userdata/
chmod -R 777 /config/www/logarr/assets/data/
