#!/usr/bin/with-contenv bash

# Clone Logarr repo
[[ ! -d /config/www/Dashboard/.git ]] && \
git clone https://github.com/Monitorr/logarr.git /config/www/Logarr

# Set permissions
chown -R abc:abc \
	/config
